### ISSUE TITLE
Komi only ever adjusts once. (Endgame branch.)

### ISSUE THREAD

**Issue by anonymousAwesome** [alreadydone/lz#42] opened 2018-08-02 07:54 UTC
Once the winrate goes above --max-wr, Endgame adjusts the komi to compensate.  But then, if the winrate drops below that amount, *the adjustment doesn't change*.  If you do a lot of board manipulation between moves then the komi adjustment will reset, but if it's just continual play it never adjusts the komi adjustment downward.

I have a game and log that I can show you if you'd like, but basically I had Endgame Leela run a very weak version of LZ against the current version of LZ.  Then I gave Endgame Leela several stones handicap, enough to trigger the komi adjustment.  Endgame Leela decided on komi of -117.070312 and opp_komi of -15360.000000.  Even 90 moves into the game, with non-endgame Leela claiming an overwhelming winrate, Endgame Leela kept claiming the komi was -117.070312 and the opp_komi was -inf.

This is probably why Endgame did so poorly in the ten-game matches.

**Comment by alreadydone** [comment] 2018-08-02 09:45
Can you try with a different network and see whether the same (he adjustment doesn't change) happens? opp_komi -15360 or -inf is definitely abnormal, and the network may not be suitable for dynamic komi or needs --pos or --neg; you can check with wrout2.exe and the command `heatmap`.

**Comment by anonymousAwesome** [comment] 2018-08-02 11:33
Yeah, I forgot Endgame doesn't work on all the weights.  It was Leela 27, but I'm on a linux box so I can't use the wrout2.exe program.

I just tested it on GX37 and I can verify that the komi doesn't update on that weight either.  Every time it establishes komi it takes about 30 seconds doing nothing before it will play a move, then each time thereafter it doesn't take that time and just reuses the established komi.  It never updates from that unless I detach and reattach the program or rewind and play a different board position.

**Comment by alreadydone** [comment] 2018-08-02 13:42
wrout2 is compiled from the wrout branch; I'll add its functionality to the komi+ branch / the next version.
So you compile yourself. Are you using the latest komi+ branch? It has a bug with the --nonslack option. With komi-v0.3 or endgame-v0.3, GX37 should be good to use; I'd like to see the log and sgf to find out the problem.

**Comment by anonymousAwesome** [comment] 2018-08-02 21:04
No, I'm using the endgame branch.  I don't think anybody knew --nonslack was even an option.

I just sent three games and the associated logs to the email listed on your github profile.

The first game used LZ 27.  The winrate started above the komi limit and dropped below it, but the komi adjustment didn't change.  

The second game used GX37. For that one I set the parameters so that it would adjust the komi at the very beginning of the game. (--min-wr=0 --max-wr=0.35 --mid-wr=0.3)   From that point on, the adjusted komi did not change.

The third game used the same settings as the second game, but I also added four white handicap stones to show the problem isn't just limited to -7.5 komi adjustment.

**Comment by alreadydone** [comment] 2018-08-03 17:31
I think in all cases the program is working as intended.
In the first game, if you test with wrout you'll find LZ 27 is not suitable for dynamic komi. Its positive komi range is especially bad, leading to the ever decreasing opp_komi. Also, this early network seem to have little sense in evaluating the positions; if you look at the NN eval, it's always near 50% and well within the [0,0.75] range you set, and that's why komi isn't adjusted.
In the second and the third games, you tried to keep black winrate within [0.65,1]. Since black is the stronger side, its winrate kept increasing and never drops below 0.65, so the komi wasn't be adjusted.

**Comment by anonymousAwesome** [comment] 2018-08-03 22:00
I'll send you a counter-example later today, but my main indicator that something is wrong is that komi only ever adjusts once. Even when the winrate increases to the point where the adjusted winrate is something like 90%, the komi adjustment doesn't change. IIRC, you can see this happen at the end of the 3rd game.

**Comment by anonymousAwesome** [comment] 2018-08-04 08:31
Okay, I emailed you another game plus the log.  This time it was black GX37 with 2 stones handicap and --min-wr 0.4, --max-wr 1, --mid-wr 0.5, and exactly 2 visits per move vs. White Leela Zero 157 with 600 visits per move.  Black adjusted the komi once at the beginning, then it never changed ever again.  The entire game, komi was 63.575779 and opp_komi was 46.816406.  Even when white's winrate rose to a whopping 87%, the komi adjustment stayed exactly the same.

...and no, the problem is not because there was a low visit count.  Black *still* took 40 seconds to calculate the appropriate komi adjustment, just like it always does on my computer.

**Comment by alreadydone** [comment] 2018-08-05 15:46
Again, since you try to control the white winrate within the range [0.4, 1] i.e. black winrate within [0, 0.6], the winrate won't get changed unless black winrate rises above 0.6, i.e. white winrate *drops* below 0.4.

**Comment by anonymousAwesome** [comment] 2018-08-05 17:38
Perhaps I misunderstand how your program works. I assumed that with a name like "dynamic komi adjustment", it would adjust the amount of komi adjustment each turn to keep the winrate near --mid-wr. Furthermore, I assumed that if the winrate dropped below the threshold after the komi adjustment was activated, the program would remove the komi adjustment until the winrate rose above the threshold again.

 Instead, your program sets the komi adjustment once and never adjusts it again. Is this intended behavior for your program?
 Because that's not dynamic, that's not what I expected from this program, and it's far less than I was hoping for.

**Comment by alreadydone** [comment] 2018-08-06 05:53
It's a matter of the parameters you set. The program tries to keep the *white winrate* within a certain *range*, with thresholds specified by --min-wr and --max-wr. If you set --min-wr 0 --max-wr 1 the winrate will surely never be adjusted, even at the beginning. In your Debugging 4.txt, you set --min-wr 0.4 --max-wr 1, with Endgame playing black, so it tries to control white winrate within [0.4,1], i.e. its own (black) winrate within [0,0.6], and it has done so successfully without needing to adjust komi again: if you look at the `NN eval` after `genmove b`, they are 0.647333, 0.517865, 0.483849, 0.493302, 0.491514, etc. and never above 0.6 (except for the first one which may be due to inaccuracy in adjustment). If you have white play a bad move, making black winrate rise above 0.6, I believe the komi will immediately be adjusted.

**Comment by anonymousAwesome** [comment] 2018-08-06 07:09
So, once winrate rises above max, Endgame won't adjust komi again until the winrate drops below min?  Forgive me for saying so, but that is a really bad way to handle komi adjustment.  It would be much better to set it up so that if winrate drops below max, komi adjustment is removed (or at least temporarily disabled) until the winrate rises above max again (and the opposite for min).

Here's the reason I believe this:  I enjoy watching strong Leela networks play against much weaker programs.  Let's say I play as white, to simplify things.  To prevent Leela from playing slack moves, I set a max-wr of, let's say 0.85.  The winrate rises to 0.9, so the komi adjustment occurs.  Let's say, 50 points.  Things go fine until Leela makes a mistake and the winrate drops.  Because of the adjusted komi, Leela now thinks that things are worse for her than they really are and starts playing bad moves.  This results in a death spiral where Leela keeps making worse and worse moves until she eventually resigns.  This is not hyperbole; I have seen this exact situation happen.

**Comment by anonymousAwesome** [comment] 2018-08-08 07:37
I want leela to play non-slack moves only when the winrate is at or above a certain percentage.  When the winrate drops below that number, I want the program to behave like normal Leela.  How do I get your program to do that?

**Comment by alreadydone** [comment] 2018-08-10 16:35
Your suggestion makes sense but isn't currently available with my code. My code only looks at the winrate after adjustment, and adjust the komi when the adjusted winrate goes out of range. In the next release it will take into account the winrate before adjustment (i.e. under the target komi).

**Comment by anonymousAwesome** [comment] 2018-08-10 22:28
Huh. That would explain why the komi adjustment kept bouncing between "on" and "off" when I tried forcing the desired behavior. Please let me know when that functionality is available.

**Comment by alreadydone** [comment] 2018-08-18 18:06
Should be fixed in both komi+ (without half precision) and komi+next (with half precision, not tested yet) branches.

**Comment by anonymousAwesome** [comment] 2018-08-18 20:35
Okay, so if I set max to 0.7 and min to 0, the adjustment will disengage when the unadjusted winrate drops below 0.7?

**Comment by alreadydone** [comment] 2018-08-19 08:06
That should be the case, yes.

**Closed as completed** 2018-11-06 06:31 UTC
